version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - .docker-data/mongo:/data/toptal-acelerator
  pg:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: myPass!23
      POSTGRES_USER: user
      POSTGRES_DB: db
